version: '3.8'

services:
  app:
    container_name: app
    build: 
      context: ./web-app  # Points to the web-app directory containing the Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
    volumes:
      - ./web-app:/app  # Mounts the web-app directory to the container's /app directory
    depends_on:
      - db

  db:
    container_name: db
    image: mongo:latest
    volumes:
      - ./db/languages.js:/docker-entrypoint-languages.d/languages.js:ro 
    ports:
      - "27017:27017"
