version: "3.10"

services:
  app:
    build: ./web-app  
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mynetwork
  ml:
    build: ./machine-learning-client
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - mynetwork
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - mynetwork
volumes:
  mongodata:
networks:
  mynetwork:

