name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create SSH directory
        run: mkdir -p ~/.ssh
      - name: Deploy to Digital Ocean
        run: |
          export SSHPASS='Cd#234GG'
          ssh-keyscan -H 159.203.121.138 >> ~/.ssh/known_hosts
          sshpass -e ssh root@159.203.121.138 "
            cd 4-containerized-app-exercise-cantopop &&
            git pull origin main &&
            docker-compose down &&
            docker-compose up -d --build
          "


