name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository
        uses: actions/checkout@v2
      - name: Digital Ocean
        run: |
          export SSHPASS='Cd#234GG'
          ssh-keyscan -H 159.203.121.138 >> ~/.ssh/known_hosts
          sshpass -e ssh -t root@159.203.121.138 
          "cd 4-containerized-app-exercise-cantopop && 
          git pull && 
          docker-compose down && 
          docker-compose up -d --build"

