name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to Digital Ocean
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 159.203.121.138 >> ~/.ssh/known_hosts
          sshpass -p 'Cd#234GG' ssh -o StrictHostKeyChecking=no root@159.203.121.138 "
          cd 4-containerized-app-exercise-cantopo && 
          docker-compose down && 
          git pull origin main && 
          docker-compose build --no-cache && 
          docker-compose up "|| true



