name: Publish Docker image

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: bailongzhao
          password: aA710814!
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: bailongzhao/easy_notes

      - name:  Build and push Docker image
        run: |
          docker tag 4-containerized-app-exercise-cantopop-app bailongzhao/easy_notes:web-app
          docker push bailongzhao/easy_notes:web-app
          docker tag 4-containerized-app-exercise-cantopop-ml bailongzhao/easy_notes:mlc
          docker push bailongzhao/easy_notes:mlc
          docker tag mongo bailongzhao/easy_notes:mongo
          docker push bailongzhao/easy_notes:mongo
